### ISSUE TITLE
Geting OOM when using new input model

### ISSUE THREAD

**Issue by ghost** [MyWorkShop/Convolutional-Neural-Networks-in-Convolution#6]
Since @D0048  got OOMs like this:
<pre>
2017-11-16 21:05:31.914727: I tensorflow/core/common_runtime/bfc_allocator.cc:685] Stats: 
Limit:                  1043988480
InUse:                  1031679232
MaxInUse:               1038011648
NumAllocs:                     104
MaxAllocSize:            472514560

2017-11-16 21:05:31.914737: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ********************xxxxxxxxx****************xxxxxxxxx*********************************xxxxxxxxxxxxx
2017-11-16 21:05:31.914750: W tensorflow/core/framework/op_kernel.cc:1192] Resource exhausted: OOM when allocating tensor with shape[5000,64,16,16]
</pre>
There is something wrong on memory caused by new input model. ( #5 and #3 )

**Comment by D0048** [comment]
Please check my review note at #3 and see if you intentionally created 25 more `small_cnn`.

**Comment by ghost** [comment]
@D0048 
The ``tf.TensorArray`` ``slicing = tf.TensorArray('float32', num * m * n)`` may causes this OMM problem.
The ``scn_input = slicing.concat()`` may create another huge ``tf.Tensor``.

**Comment by ghost** [comment]
@D0048 ,maybe I won't fix this pronlem.
You may revert these pl(#3 and #5 ).

**Comment by D0048** [comment]
@mwsht That's fine, I would just keep the original model till I get access to a larger graphic memory. However, I do want to know your graphic memory consumption during training. Could you please just check and tell me?

**Comment by ghost** [comment]
@D0048 , maybe you can delete these configurations  below:
```python
        config = tf.ConfigProto(
            inter_op_parallelism_threads = 256,
            intra_op_parallelism_threads = 64
        )
```
It's just a stupid way try to speed up the code.

**Comment by D0048** [comment]
Solved: looks working using `tf.layers.conv2d` replacing the one you wrote and reducing validation batch size.
